In [1]:
import netCDF4
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
filename = "/Users/mgjeon/workspace/12673_20170906_000000.nc"

In [7]:
nc = netCDF4.Dataset(filename, 'r')

x = np.array(nc.variables['x'])
y = np.array(nc.variables['y'])
z = np.array(nc.variables['z'])

Bx = np.array(nc.variables['Bx']).transpose(2, 1, 0)
By = np.array(nc.variables['By']).transpose(2, 1, 0)
Bz = np.array(nc.variables['Bz']).transpose(2, 1, 0)

dx = np.diff(x)[0]
dy = np.diff(y)[0]
dz = np.diff(z)[0]

Bx.shape, dx, dy, dz

((513, 257, 257), 0.48969578700000227, 0.6377433539999942, 0.637743354)

In [11]:
from findiff import Curl

In [12]:
curl = Curl(h=[dx, dy, dz])

In [13]:
B = np.stack([Bx, By, Bz])
J = curl(B)

J.shape, B.shape

((3, 513, 257, 257), (3, 513, 257, 257))

In [16]:
a = [1, 2, 3]
b = [4, 5, 6]
np.cross(a, b)

array([-3,  6, -3])

In [18]:
A = np.array([a, a])
B = np.array([b, b])

np.cross(A, B)

array([[-3,  6, -3],
       [-3,  6, -3]])

In [19]:
A.shape

(2, 3)

In [15]:
J.reshape(-1, 3)

array([[-2.75378470e+02, -1.02033982e+02,  5.84179645e-01],
       [ 5.64987825e-02, -4.51712117e-02, -4.87601450e-02],
       [-3.62332724e-02, -2.47748552e-02, -1.67849924e-02],
       ...,
       [ 9.67016675e-01,  9.56757185e-01,  9.47258031e-01],
       [ 9.37597001e-01,  9.26309549e-01,  9.11462721e-01],
       [ 8.93126122e-01,  8.76518707e-01,  8.86941358e-01]])

In [ ]:
JxB = np.cross(J, B, axis=)