In [1]:
noaanum = 12673
obsdate = "20170906_090000"

# ISEE / Kusano
nc_file = f"/mnt/obsdata/isee_nlfff_v1.2/{noaanum}/{noaanum}_{obsdate}.nc"

In [2]:
from tool.metric import load_nc_file, calculate_derivative

In [3]:
x, y, z, Bx, By, Bz, Bx_pot, By_pot, Bz_pot = load_nc_file(nc_file)

In [4]:
dx = x[1] - x[0]  # Mm
dy = y[1] - y[0]  # Mm
dz = z[1] - z[0]  # Mm

Lx = x[-1] - x[0]  # Mm
Ly = y[-1] - y[0]  # Mm
Lz = z[-1] - z[0]  # Mm

In [5]:
(
    B,
    norm_B,
    J,
    norm_J,
    JxB,
    norm_JxB,
    div_B,
    norm_div_B,
    laplacian_B,
    norm_laplacian_B,
    energy_density_B,
) = calculate_derivative(Bx, By, Bz, dx, dy, dz)

In [6]:
import numpy as np 
import scipy.signal as ss

In [7]:
np.max(laplacian_B)

118996.61878377522

In [8]:
np.argmax(laplacian_B)

46866777

In [9]:
ss.argrelmax(laplacian_B)

(array([1, 1, 1, ..., 1, 1, 1]),
 array([  0,   0,   0, ..., 512, 512, 512]),
 array([  0,   0,   0, ..., 256, 256, 256]),
 array([  0,  70,  79, ..., 254, 255, 256]))

In [10]:
from tool.write_vtk import create_mesh

In [11]:
mesh = create_mesh(nc_file)

In [12]:
mesh["laplacianB"] = laplacian_B.transpose(2, 1, 0, 3).reshape(-1, 3)

In [32]:
mesh_dir = "/mnt/userdata/jeon_mg/series/result"

In [33]:
import os

In [34]:
vtk_dir = os.path.join(mesh_dir, str(noaanum)+'_vtk')
os.makedirs(vtk_dir, exist_ok=True)

In [35]:
vtk_path = os.path.join(vtk_dir, os.path.basename(nc_file).split('.')[0]) + '.vtk'
vtk_path

'/mnt/userdata/jeon_mg/series/12673_vtk/12673_20170906_090000.vtk'

In [36]:
mesh.save(vtk_path)